APPLICATION = lora3a-lorawan
BOARD ?= berta-h10
RIOTBASE ?= $(CURDIR)/../RIOT
LORA3ABASE ?= $(CURDIR)/../lora3a-boards
EXTERNAL_BOARD_DIRS=$(LORA3ABASE)/boards
EXTERNAL_MODULE_DIRS=$(LORA3ABASE)/modules
EXTERNAL_PKG_DIRS=$(LORA3ABASE)/pkg
DEVELHELP ?= 1
QUIET ?= 1
PORT ?= /dev/ttyUSB0

USEMODULE += saml21_cpu_debug
USEMODULE += saml21_backup_mode
USEMODULE += saul_default
USEMODULE += fram
USEMODULE += periph_cpuid

USEMODULE += netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_lorawan
USEMODULE += gnrc_pktdump
USEMODULE += gnrc_txtsnd

USEMODULE += shell
USEMODULE += shell_cmds_default
USEMODULE += shell_extra_commands
USEMODULE += od_string

CFLAGS += -DSX127X_PARAM_PASELECT=SX127X_PA_RFO

DEVEUI ?= 0000000000000000
APPEUI ?= 0000000000000000
APPKEY ?= 00000000000000000000000000000000

CFLAGS += -DCONFIG_LORAMAC_DEV_EUI_DEFAULT=\"$(DEVEUI)\"
CFLAGS += -DCONFIG_LORAMAC_APP_EUI_DEFAULT=\"$(APPEUI)\"
CFLAGS += -DCONFIG_LORAMAC_APP_KEY_DEFAULT=\"$(APPKEY)\"

CFLAGS += -DCONFIG_GNRC_NETIF_LORAWAN_NETIF_HDR
CFLAGS += -DCONFIG_LORAMAC_DEFAULT_JOIN_PROCEDURE_OTAA
CFLAGS += -DCONFIG_LORAMAC_DEFAULT_TX_MODE_UNCNF
CFLAGS += -DCONFIG_LORAMAC_REGION_EU_868
CFLAGS += -DCONFIG_LORAMAC_DEFAULT_TX_POWER_14
CFLAGS += -DCONFIG_LORAMAC_DEFAULT_DR5
ifndef CONFIG_GNRC_PKTBUF_SIZE
  CFLAGS += -DCONFIG_GNRC_PKTBUF_SIZE=512
endif

USEMODULE += printf_float
USEMODULE += senseair

CFLAGS += -DACME0_BUS_MODE=MODE_I2C

ACME_PORT ?= 1

ifeq ($(ACME_PORT), 0)
CFLAGS += -DSENSEAIR_I2C_DEV=ACME0_I2C_DEV -DSENSEAIR_ENABLE_PIN=GPIO_PIN\(PA,19\) -DACME_BUS_POWER_PIN=ACME0_POWER_PIN
endif

ifeq ($(ACME_PORT), 1)
CFLAGS += -DACME1_BUS_MODE=MODE_I2C
CFLAGS += -DSENSEAIR_I2C_DEV=ACME1_I2C_DEV -DSENSEAIR_ENABLE_PIN=GPIO_PIN\(PB,23\) -DACME_BUS_POWER_PIN=ACME1_POWER_PIN
endif

ifeq ($(ACME_PORT), 2)
CFLAGS += -DACME2_BUS_MODE=MODE_I2C
CFLAGS += -DSENSEAIR_I2C_DEV=ACME2_I2C_DEV -DSENSEAIR_ENABLE_PIN=GPIO_PIN\(PA,7\) -DACME_BUS_POWER_PIN=ACME2_POWER_PIN
endif

include $(RIOTBASE)/Makefile.include
