APPLICATION = lora3a-lorawan
BOARD ?= lora3a-h10
RIOTBASE ?= $(CURDIR)/../RIOT
LORA3ABASE ?= $(CURDIR)/../lora3a-boards
EXTERNAL_BOARD_DIRS=$(LORA3ABASE)/boards
EXTERNAL_MODULE_DIRS=$(LORA3ABASE)/modules
EXTERNAL_PKG_DIRS=$(LORA3ABASE)/pkg
DEVELHELP ?= 1
QUIET ?= 1
PORT ?= /dev/ttyUSB0

USEMODULE += saml21_cpu_debug
USEMODULE += saml21_backup_mode
USEMODULE += saul_default
USEMODULE += fram
USEMODULE += periph_cpuid

USEMODULE += netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_lorawan
USEMODULE += gnrc_pktdump
USEMODULE += gnrc_txtsnd

USEMODULE += shell
USEMODULE += shell_cmds_default
USEMODULE += shell_extra_commands
USEMODULE += od_string

DEVEUI ?= 0000000000000000
APPEUI ?= 0000000000000000
APPKEY ?= 00000000000000000000000000000000

CFLAGS += -DCONFIG_LORAMAC_DEV_EUI_DEFAULT=\"$(DEVEUI)\"
CFLAGS += -DCONFIG_LORAMAC_APP_EUI_DEFAULT=\"$(APPEUI)\"
CFLAGS += -DCONFIG_LORAMAC_APP_KEY_DEFAULT=\"$(APPKEY)\"

CFLAGS += -DCONFIG_GNRC_NETIF_LORAWAN_NETIF_HDR
CFLAGS += -DCONFIG_LORAMAC_DEFAULT_JOIN_PROCEDURE_OTAA
CFLAGS += -DCONFIG_LORAMAC_DEFAULT_TX_MODE_UNCNF
CFLAGS += -DCONFIG_LORAMAC_REGION_EU_868
CFLAGS += -DCONFIG_LORAMAC_DEFAULT_ADR=1
ifndef CONFIG_GNRC_PKTBUF_SIZE
  CFLAGS += -DCONFIG_GNRC_PKTBUF_SIZE=512
endif

USEMODULE += printf_float
USEMODULE += senseair

ACMEBUS ?= 1

ifeq ($(ACMEBUS),1)
    CFLAGS += -DENABLE_ACME1=MODE_I2C -DSENSEAIR_I2C_DEV=ACME1_I2C_DEV -DSENSEAIR_ENABLE_PIN=GPIO_PIN\(PB,23\) -DACMEBUS_ENABLE=GPIO_PIN\(PA,28\)
else ifeq ($(ACMEBUS),2)
    CFLAGS += -DENABLE_ACME2=MODE_I2C -DSENSEAIR_I2C_DEV=ACME2_I2C_DEV -DSENSEAIR_ENABLE_PIN=GPIO_PIN\(PA,7\) -DACMEBUS_ENABLE=GPIO_PIN\(PA,31\)
else
    $(error Invalid value for ACMEBUS; should be 1 or 2)
endif

include $(RIOTBASE)/Makefile.include
